// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fcm.proto

package fcm_xmpp_protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DownstreamMessageRequest struct {
	To                       string          `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Condition                string          `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	MessageId                string          `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	CollapseKey              string          `protobuf:"bytes,4,opt,name=collapse_key,json=collapseKey,proto3" json:"collapse_key,omitempty"`
	Priority                 string          `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	ContentAvailable         bool            `protobuf:"varint,6,opt,name=content_available,json=contentAvailable,proto3" json:"content_available,omitempty"`
	MutableContent           bool            `protobuf:"varint,7,opt,name=mutable_content,json=mutableContent,proto3" json:"mutable_content,omitempty"`
	TimeToLive               int32           `protobuf:"varint,8,opt,name=time_to_live,json=timeToLive,proto3" json:"time_to_live,omitempty"`
	DeliveryReceiptRequested bool            `protobuf:"varint,9,opt,name=delivery_receipt_requested,json=deliveryReceiptRequested,proto3" json:"delivery_receipt_requested,omitempty"`
	DryRun                   bool            `protobuf:"varint,10,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	Data                     *_struct.Struct `protobuf:"bytes,11,opt,name=data,proto3" json:"data,omitempty"`
	Notification             *_struct.Struct `protobuf:"bytes,12,opt,name=notification,proto3" json:"notification,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}        `json:"-"`
	XXX_unrecognized         []byte          `json:"-"`
	XXX_sizecache            int32           `json:"-"`
}

func (m *DownstreamMessageRequest) Reset()         { *m = DownstreamMessageRequest{} }
func (m *DownstreamMessageRequest) String() string { return proto.CompactTextString(m) }
func (*DownstreamMessageRequest) ProtoMessage()    {}
func (*DownstreamMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe29398eb47a232, []int{0}
}

func (m *DownstreamMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownstreamMessageRequest.Unmarshal(m, b)
}
func (m *DownstreamMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownstreamMessageRequest.Marshal(b, m, deterministic)
}
func (m *DownstreamMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownstreamMessageRequest.Merge(m, src)
}
func (m *DownstreamMessageRequest) XXX_Size() int {
	return xxx_messageInfo_DownstreamMessageRequest.Size(m)
}
func (m *DownstreamMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownstreamMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownstreamMessageRequest proto.InternalMessageInfo

func (m *DownstreamMessageRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *DownstreamMessageRequest) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

func (m *DownstreamMessageRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *DownstreamMessageRequest) GetCollapseKey() string {
	if m != nil {
		return m.CollapseKey
	}
	return ""
}

func (m *DownstreamMessageRequest) GetPriority() string {
	if m != nil {
		return m.Priority
	}
	return ""
}

func (m *DownstreamMessageRequest) GetContentAvailable() bool {
	if m != nil {
		return m.ContentAvailable
	}
	return false
}

func (m *DownstreamMessageRequest) GetMutableContent() bool {
	if m != nil {
		return m.MutableContent
	}
	return false
}

func (m *DownstreamMessageRequest) GetTimeToLive() int32 {
	if m != nil {
		return m.TimeToLive
	}
	return 0
}

func (m *DownstreamMessageRequest) GetDeliveryReceiptRequested() bool {
	if m != nil {
		return m.DeliveryReceiptRequested
	}
	return false
}

func (m *DownstreamMessageRequest) GetDryRun() bool {
	if m != nil {
		return m.DryRun
	}
	return false
}

func (m *DownstreamMessageRequest) GetData() *_struct.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DownstreamMessageRequest) GetNotification() *_struct.Struct {
	if m != nil {
		return m.Notification
	}
	return nil
}

type DownstreamMessageResponse struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	MessageId            string   `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MessageType          string   `protobuf:"bytes,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ErrorDescription     string   `protobuf:"bytes,5,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownstreamMessageResponse) Reset()         { *m = DownstreamMessageResponse{} }
func (m *DownstreamMessageResponse) String() string { return proto.CompactTextString(m) }
func (*DownstreamMessageResponse) ProtoMessage()    {}
func (*DownstreamMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe29398eb47a232, []int{1}
}

func (m *DownstreamMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownstreamMessageResponse.Unmarshal(m, b)
}
func (m *DownstreamMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownstreamMessageResponse.Marshal(b, m, deterministic)
}
func (m *DownstreamMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownstreamMessageResponse.Merge(m, src)
}
func (m *DownstreamMessageResponse) XXX_Size() int {
	return xxx_messageInfo_DownstreamMessageResponse.Size(m)
}
func (m *DownstreamMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownstreamMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownstreamMessageResponse proto.InternalMessageInfo

func (m *DownstreamMessageResponse) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *DownstreamMessageResponse) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *DownstreamMessageResponse) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func (m *DownstreamMessageResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DownstreamMessageResponse) GetErrorDescription() string {
	if m != nil {
		return m.ErrorDescription
	}
	return ""
}

type UpstreamMessage struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	MessageId            string   `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Data                 string   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpstreamMessage) Reset()         { *m = UpstreamMessage{} }
func (m *UpstreamMessage) String() string { return proto.CompactTextString(m) }
func (*UpstreamMessage) ProtoMessage()    {}
func (*UpstreamMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe29398eb47a232, []int{2}
}

func (m *UpstreamMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpstreamMessage.Unmarshal(m, b)
}
func (m *UpstreamMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpstreamMessage.Marshal(b, m, deterministic)
}
func (m *UpstreamMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpstreamMessage.Merge(m, src)
}
func (m *UpstreamMessage) XXX_Size() int {
	return xxx_messageInfo_UpstreamMessage.Size(m)
}
func (m *UpstreamMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UpstreamMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UpstreamMessage proto.InternalMessageInfo

func (m *UpstreamMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *UpstreamMessage) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *UpstreamMessage) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *UpstreamMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ACKMessage struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	MessageId            string   `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MessageType          string   `protobuf:"bytes,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACKMessage) Reset()         { *m = ACKMessage{} }
func (m *ACKMessage) String() string { return proto.CompactTextString(m) }
func (*ACKMessage) ProtoMessage()    {}
func (*ACKMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffe29398eb47a232, []int{3}
}

func (m *ACKMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACKMessage.Unmarshal(m, b)
}
func (m *ACKMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACKMessage.Marshal(b, m, deterministic)
}
func (m *ACKMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACKMessage.Merge(m, src)
}
func (m *ACKMessage) XXX_Size() int {
	return xxx_messageInfo_ACKMessage.Size(m)
}
func (m *ACKMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ACKMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ACKMessage proto.InternalMessageInfo

func (m *ACKMessage) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ACKMessage) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *ACKMessage) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func init() {
	proto.RegisterType((*DownstreamMessageRequest)(nil), "fcm_xmpp_protobuf.DownstreamMessageRequest")
	proto.RegisterType((*DownstreamMessageResponse)(nil), "fcm_xmpp_protobuf.DownstreamMessageResponse")
	proto.RegisterType((*UpstreamMessage)(nil), "fcm_xmpp_protobuf.UpstreamMessage")
	proto.RegisterType((*ACKMessage)(nil), "fcm_xmpp_protobuf.ACKMessage")
}

func init() { proto.RegisterFile("fcm.proto", fileDescriptor_ffe29398eb47a232) }

var fileDescriptor_ffe29398eb47a232 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0xb5, 0x69, 0x92, 0x26, 0x93, 0xa8, 0x7f, 0x2c, 0xa4, 0x9a, 0xa8, 0x48, 0x21, 0x17,
	0x22, 0x55, 0x4a, 0x25, 0x38, 0xc2, 0xa5, 0x6a, 0x2f, 0xa8, 0x70, 0x59, 0xca, 0x15, 0xcb, 0xf1,
	0x4e, 0x22, 0x8b, 0xdd, 0xb5, 0xf1, 0xce, 0x06, 0xf6, 0xbd, 0x78, 0x1f, 0x5e, 0x05, 0xad, 0xed,
	0x6d, 0xd5, 0x2a, 0x82, 0x43, 0x6f, 0x33, 0xdf, 0xf7, 0x4d, 0x32, 0x3b, 0x3f, 0xc3, 0x78, 0xa3,
	0x8a, 0x95, 0x75, 0x86, 0x0c, 0x3b, 0xdd, 0xa8, 0x42, 0xfc, 0x2a, 0xac, 0x15, 0xbe, 0x5f, 0xd7,
	0x9b, 0xd9, 0xf9, 0xd6, 0x98, 0x6d, 0x8e, 0x97, 0x9d, 0x70, 0x59, 0x91, 0xab, 0x15, 0x85, 0x81,
	0xc5, 0x9f, 0x03, 0xe0, 0x37, 0xe6, 0x67, 0x59, 0x91, 0x43, 0x59, 0x7c, 0xc6, 0xaa, 0x92, 0x5b,
	0x4c, 0xf1, 0x47, 0x8d, 0x15, 0xb1, 0x23, 0xe8, 0x91, 0xe1, 0xc9, 0x3c, 0x59, 0x8e, 0xd3, 0x1e,
	0x19, 0x76, 0x0e, 0x63, 0x65, 0xca, 0x4c, 0x93, 0x36, 0x25, 0xef, 0x79, 0xf9, 0x41, 0x60, 0xaf,
	0x00, 0x8a, 0x30, 0x2f, 0x74, 0xc6, 0x0f, 0x82, 0x1d, 0x95, 0x8f, 0x19, 0x7b, 0x0d, 0x53, 0x65,
	0xf2, 0x5c, 0xda, 0x0a, 0xc5, 0x77, 0x6c, 0x78, 0xdf, 0x07, 0x26, 0x9d, 0x76, 0x8b, 0x0d, 0x9b,
	0xc1, 0xc8, 0x3a, 0x6d, 0x9c, 0xa6, 0x86, 0x0f, 0xbc, 0x7d, 0xdf, 0xb3, 0x0b, 0x38, 0x55, 0xa6,
	0x24, 0x2c, 0x49, 0xc8, 0x9d, 0xd4, 0xb9, 0x5c, 0xe7, 0xc8, 0x87, 0xf3, 0x64, 0x39, 0x4a, 0x4f,
	0xa2, 0x71, 0xd5, 0xe9, 0xec, 0x0d, 0x1c, 0x17, 0x35, 0xb5, 0xa5, 0x88, 0x1e, 0x3f, 0xf4, 0xd1,
	0xa3, 0x28, 0x5f, 0x07, 0x95, 0xcd, 0x61, 0x4a, 0xba, 0x40, 0x41, 0x46, 0xe4, 0x7a, 0x87, 0x7c,
	0x34, 0x4f, 0x96, 0x83, 0x14, 0x5a, 0xed, 0xce, 0x7c, 0xd2, 0x3b, 0x64, 0x1f, 0x60, 0x96, 0x61,
	0xeb, 0xb9, 0x46, 0x38, 0x54, 0xa8, 0x2d, 0x09, 0x17, 0xee, 0x83, 0x19, 0x1f, 0xfb, 0x5f, 0xe5,
	0x5d, 0x22, 0x0d, 0x81, 0xb4, 0xf3, 0xd9, 0x19, 0x1c, 0x66, 0xed, 0x60, 0x5d, 0x72, 0xf0, 0xd1,
	0x61, 0xe6, 0x9a, 0xb4, 0x2e, 0xd9, 0x05, 0xf4, 0x33, 0x49, 0x92, 0x4f, 0xe6, 0xc9, 0x72, 0xf2,
	0xf6, 0x6c, 0x15, 0x20, 0xad, 0x3a, 0x48, 0xab, 0x2f, 0x1e, 0x52, 0xea, 0x43, 0xec, 0x3d, 0x4c,
	0x4b, 0x43, 0x7a, 0xa3, 0x95, 0xf4, 0xa7, 0x9f, 0xfe, 0x7b, 0xe8, 0x51, 0x78, 0xf1, 0x3b, 0x81,
	0x97, 0x7b, 0x08, 0x57, 0xd6, 0x94, 0x15, 0x32, 0x06, 0xfd, 0x8d, 0x33, 0x45, 0x84, 0xec, 0xeb,
	0x27, 0x20, 0x7b, 0x7b, 0x40, 0x76, 0x36, 0x35, 0x16, 0x23, 0xe9, 0x49, 0xd4, 0xee, 0x1a, 0x8b,
	0xec, 0x05, 0x0c, 0xd0, 0x39, 0xe3, 0x22, 0xe4, 0xd0, 0xb4, 0x08, 0x7d, 0x21, 0x32, 0xac, 0x94,
	0xd3, 0xd6, 0x7f, 0x4b, 0xe0, 0x7c, 0xe2, 0x8d, 0x9b, 0x07, 0x7d, 0x41, 0x70, 0xfc, 0xd5, 0x3e,
	0xda, 0x79, 0xef, 0xae, 0x33, 0x18, 0x29, 0x49, 0xb8, 0x35, 0xae, 0x89, 0x9b, 0xde, 0xf7, 0xff,
	0x7b, 0x90, 0x2c, 0x22, 0x08, 0x3b, 0xfa, 0x7a, 0xf1, 0x0d, 0xe0, 0xea, 0xfa, 0xb6, 0xfb, 0xc3,
	0xa7, 0xef, 0xff, 0xd9, 0x87, 0x59, 0x0f, 0x3d, 0xab, 0x77, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x33, 0xd3, 0x31, 0x04, 0xb3, 0x03, 0x00, 0x00,
}
